### PR TITLE
Section#within - solution for #21

### LINKED ISSUE #21: individual Section in sections do not exec block
From site_prism created by [tgaff](https://github.com/tgaff): natritmeyer/site_prism#395  

# Issue to raise for SitePrism framework
```rb
  section :my_section, MySection, 'div.locator'

  @page.my_section do |section|
    section.something # executes
  end

 sections :my_sections, MySection, 'div.locator'  #

  @page.my_sections.first do |section|
    section.something # does not execute block
  end
```

While the second behavior is not explicitly documented, one would it expect it to work since `:sections` is in many ways an Array-like of `:section`.  Not sure whether this should be considered a bug or feature-request, but failing to execute the block could lead to incorrectly-passing tests.

## Environment
- OSX
- SitePrism itself at recent master 4c568ddf7029273fcb02c3230b21a82b11d54c44
- SitePrism's own cucumber scenarios
- firefox default

## Expected Behavior
We can exec inside a section similar to Capybara `within` functionality on an individual section.  But on an array of sections generated by `:sections` this does not work.  
I expected that my block would be executed when passed as `@page.my_sections {|s| raise 'ermagerd'}`

## Actual Behavior
Code in the block is not exec'd

## Steps to reproduce
1.  clone https://github.com/tgaff/site_prism/tree/tg/sections_dont_exec_blocks
1. `cucumber -r features`
1. observe test failure

## cucumber scenario

In the below I verify that on the Section features we do execute the contents of the block.
However when it comes to the Sections features, the same functionality fails - the block is not executed.  Specifically the tests fail with:

```sh
    Then I can execute in the context of a section using a block # features/step_definitions/sections_steps.rb:22

      expected: 2
           got: 0

      (compared using ==)
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/sections_steps.rb:39:in `"I can execute in the context of a section using a block"'
      features/sections.feature:21:in `Then I can execute in the context of a section using a block'

Failing Scenarios:
cucumber features/sections.feature:19 # Scenario: access elements in the section by passing a block

91 scenarios (1 failed, 90 passed)
229 steps (1 failed, 228 passed)
0m23.693s
```

Patch that reproduces this behavior

```
diff --git a/features/sections.feature b/features/sections.feature
index 1705336..4f9aee8 100644
--- a/features/sections.feature
+++ b/features/sections.feature
@@ -15,3 +15,7 @@ Feature: Interaction with groups of elements
   Scenario: anonymous sections collection
     When I navigate to the nested section page
     Then I can see a collection of anonymous sections
+
+  Scenario: access elements in the section by passing a block
+    When I navigate to the nested section page
+    Then I can execute in the context of a section using a block
diff --git a/features/step_definitions/section_steps.rb b/features/step_definitions/section_steps.rb
index a56cd57..45e5bb0 100644
--- a/features/step_definitions/section_steps.rb
+++ b/features/step_definitions/section_steps.rb
@@ -12,13 +12,19 @@ Then('I can see a section in a section') do
 end

 Then('I can access elements within the section using a block') do
+  block_inner_executions = 0
+
   expect(@test_site.home).to have_people

   @test_site.home.people do |section|
+    block_inner_executions += 1
+
     expect(section.headline.text).to eq('People')

     expect(section).to have_individuals(count: 4)
   end
+
+  expect(block_inner_executions).to eq 1
 end

 Then('I cannot access elements that are not in the section using a block') do
diff --git a/features/step_definitions/sections_steps.rb b/features/step_definitions/sections_steps.rb
index f57cbe7..4e1f0c9 100644
--- a/features/step_definitions/sections_steps.rb
+++ b/features/step_definitions/sections_steps.rb
@@ -17,3 +17,24 @@ Then('I can see a collection of anonymous sections') do

   expect(anonymous_sections.size).to eq(2)
 end
+
+
+Then('I can execute in the context of a section using a block') do
+  block_inner_executions = 0
+
+  expect(@test_site.nested_sections).to have_search_results(count: 4)
+
+  @test_site.nested_sections.search_results.first do |sec|
+    block_inner_executions += 1
+    expect(sec).to be_an_instance_of(SitePrism::Section)
+    expect(sec).to have_text('Result 0')
+  end
+
+  @test_site.nested_sections.search_results.last do |sec|
+    block_inner_executions += 1
+    expect(sec).to be_an_instance_of(SitePrism::Section)
+    expect(sec).to have_text('Result 3')
+  end
+
+  expect(block_inner_executions).to eq 2
+end
```

### PR DESCRIPTION
**Pull request by tgaff**
## Overview

Hi Luke,
This is one of the potential ways to resolve #21 that I discussed so long ago.  I'm sorry it took this long to get you anything for this.  Even more so, since this turned out to be much simpler than I anticipated.

#### Issue Review #21 
In #21 we had the problem that the following was OK:

```rb
page.my_section do |sec|
  expect(sec).to have_secs_element
end
```

But the following silently ignored the block because when the block is executed in the above, it's executed as part of the `initialize` method.
```rb
page.my_sections.first do |sec|
  expect(sec).to have_secs_element
end
```

**In this case the sections are initialized and put into an Array.  Initialization has passed and Array#first doesn't use a block.**

#### This change
With this change you can do basically the same thing by calling `#within`.
```rb
page.my_sections.first.within do |sec|
  expect(sec).to have_secs_element
end
```

### Other Alternatives

We could implement a `SectionsCollection` class that serves as the `Array` for Sections.  
We would need the basic methods such as:
* `first`
* `last`
* `map`
* `each`

These could take a block as needed.

Capybara does something similar with [Capybara::Result](https://rubydoc.info/github/teamcapybara/capybara/master/Capybara/Result) which is the result class for `page.all('.locator')`

That would obviously be more complex and I'm not sure we have a strong need for it yet, thoughts? Regardless, I think this actually would be useful as a start for that, as we'd still want a good way to execute easily in the context of a section at will.

## TODO / Questions

* docs -   Figured I would see how you felt about it first @luke-hill 
* do we want to discourage the use of sending a block to Section#new (which is maybe not obvious to many users) and instead encourage using #within ?
* I want to give this a test on one of my repos JIC
* should I bump the version?
* I added a pry **dev** dependency - it's a very common gem and I end up pulling it in every time I work on site-prism then undoing that add.

### CODE REVIEW

File: lib/site_prism/section.rb [hunk 1]
```diff
@@ -31,6 +31,10 @@ def initialize(parent, root_element)
       Capybara.within(@root_element) { yield(self) } if block_given?
```
Comment (luke-hill) [inline lib/site_prism/section.rb]: lets refactor this line

**Comment by luke-hill** [comment]
p.s. ignore the failure. I need to do a slight bit of refactoring.

Since the latest 2.5 cut came out, the runtimes have actually **improved**. I just need to make a couple of refactors to the test codebase and isolate the runtimes, because it's loads of duplication I can remove.

**Comment by luke-hill** [comment]
Hi @tgaff 

What do you want to do with this, I've only put a small refactor requested, but this is essentially RtM unless you want to make some additional fixes?

**Comment by tgaff** [comment]
I know I'm forever slow.  Sorry.  I'll write some docs and make the change you requested!  
I wanted to test this in a bigger code-base but haven't been able to yet (need to do some upgrades on that).

**Comment by luke-hill** [comment]
Ping @tgaff

**Comment by tgaff** [comment]
Sorry Luke, changed jobs and don't have that bigger code-base to test on now.  

I'll write up the docs and get this in.  Sorry once again.

**Comment by tgaff** [comment]
Ok, I added a little documentation and rebased it.  Tests are still failing but I think its the same failure as on master.  Maybe a Capybara API update?

**Comment by luke-hill** [comment]
@tgaff I'm busy for 1 or 2 weeks. For now can you add an upper restriction of say 3.29 to capybara and see if that helps.

It's one test and one missing method, so that's likely it.

File: lib/site_prism/section.rb (hunk 1 above)
Comment (luke-hill) [reply lib/site_prism/section.rb]: ping here.

**Comment by tgaff** [comment]
Luke your thoughts on 3.30 being the issue were correct.  Thanks!

File: README.md [hunk 2]
```diff
@@ -937,6 +936,16 @@ Then(/^the home page menu contains a link to the various search functions$/) do
 end
 ```
 
+Note that on individual sections it's possible to pass a block directly to the section without using `within`.  Because the block is executed only during Section initialization this won't work when accessing a single Section from an array of Sections.  For that reason we recommend using `within` which works in either case.
```
[the remark this answers is not in the document]
Comment (tgaff) [reply README.md]: ✔️

**Comment by luke-hill** [comment]
Cheers travis. I think I'll dig into this issue a bit more and maybe put a more strict check on gem version, but this PR is rtm!
